import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './Component/NavBar'
import Footer from './Component/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Best Restaurant in Dhaka',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        {children}
        <Footer></Footer>
        </body>
    </html>
  )
}
